import './styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from "next/font/google";
import Layout from './containers/layout/layout';
import { useEffect } from 'react';
import { themeChange } from 'theme-change';


export const metadata: Metadata = {
  title: 'Box Office',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body  className={inter.className}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}