import type { Metadata } from 'next'
import { ThemeProvider } from "@mui/material";
import theme from "@/src/app/styles/theme";

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import Layout from '@/src/app/containers/dashboard/layout'



export const metadata: Metadata = {
  title: 'Box Office',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </head>
      <body>
        <ThemeProvider theme={theme}>
<<<<<<< HEAD
          
            {children}
          
=======
          <Layout>
            {children}
          </Layout>
>>>>>>> 60c7d63e113c6e3503d59fb8200dd4d3f15b858f
        </ThemeProvider>
      </body>
    </html>
  )
}